# Generated by Django 4.2.4 on 2023-09-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comments_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user',
        ),
    ]
